Change to classes
LangiviTechnology/twig.js pull request #2
Opened 2021-11-08 12:33 UTC by dmytro-lt

2021-11-09 10:23 UTC, andriy-kozlytski requested changes

2021-11-09 10:23 UTC, andriy-kozlytski commented on src/twig.compiler.js
> +        Twig;
Why is  this need?

2021-11-09 10:23 UTC, andriy-kozlytski commented on src/twig.compiler.js
> +    class TwigCompilerModule {
It mus be class field

2021-11-09 10:23 UTC, andriy-kozlytski commented on src/twig.compiler.js
> +    // Twig.compiler.wrap = function (id, tokens) {
Method of class

2021-11-09 14:02 UTC, andriy-kozlytski requested changes
Should export class

2021-11-09 14:02 UTC, andriy-kozlytski commented on src/twig.compiler.js
> +        module() {
It isn't method it's field

2021-11-09 14:02 UTC, andriy-kozlytski commented on src/twig.compiler.js
> +    return Twig
shouldn't return

2021-11-09 14:02 UTC, andriy-kozlytski commented on src/twig.compiler.js
>          module: {}
this is field of TwigCompiler

2021-11-09 16:46 UTC, lodry requested changes

2021-11-09 16:46 UTC, lodry commented on src/twig.compiler.js
> +            fn: (id, tokens) => 'twig({id:"' + id.replace('"', '\\"') + '", data:' + tokens + ', precompiled: true});\n';
why is it object?

2021-11-10 09:51 UTC, lodry requested changes

2021-11-10 09:51 UTC, lodry commented on src/twig.compiler.js
>              output = Twig.compiler.wrap(id, tokens);
it is not injected in oyur class better `this.wrap(id, tokens)`

2021-11-10 09:51 UTC, lodry commented on src/twig.compiler.js
> +    constructor() {
inject global Twig object

2021-11-10 09:51 UTC, lodry commented on src/twig.compiler.js
> +export default class TwigCompiler {
you should export not class but instantiated object

2021-11-10 09:51 UTC, lodry commented on src/twig.compiler.js
> +    module: {}
why is it empty??

2021-11-11 12:02 UTC, andriy-kozlytski requested changes

2021-11-11 12:02 UTC, andriy-kozlytski commented on src/twig.compiler.js
> +            if (this.module[options.module] === undefined) {
replace to
this.Twig.compiler.

2021-11-11 12:02 UTC, andriy-kozlytski commented on src/twig.compiler.js
> +            output = this.wrap(id, tokens);
same

2021-11-11 12:02 UTC, andriy-kozlytski commented on src/twig.compiler.js
> +            output = this.module[options.module](id, tokens, options.twig);
same

2021-11-16 19:35 UTC, lodry approved these changes

2021-11-16 19:35 UTC, merged