Added missing functions
LangiviTechnology/twig.js pull request #5
Opened 2021-11-17 15:04 UTC by dmytro-lt

https://app.asana.com/0/1157793729216339/1201246276117419

2021-11-17 15:53 UTC, lodry commented on src/twig.functions.js
> +            var reader = new FileReader()
use node js `fs` package

2021-11-17 15:54 UTC, lodry commented on src/twig.functions.js
> +        include(file) {
please explain what `include` should do

2021-11-18 10:49 UTC, andriy-kozlytski requested changes

2021-11-18 10:49 UTC, andriy-kozlytski commented on src/twig.timezones.js
> +}
Some countries 
have a same zone
have a lot of zones, ex. Russia have 11 zones

2022-06-27 21:43 UTC, closed without merging